In [1]:
import numpy as np

### Scalars

In [11]:
s = np.array(5)

In [12]:
s

array(5)

### Vectors

In [4]:
v = np.array([5,-2,4])

In [5]:
v

array([ 5, -2,  4])

### Matrices

In [6]:
m = np.array([[5,12,6],[-3,0,14]])

In [7]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

### Data types

In [13]:
type(s)

numpy.ndarray

In [8]:
type(v)

numpy.ndarray

In [9]:
type(m)

numpy.ndarray

### Data shape

In [14]:
m.shape

(2, 3)

In [15]:
v.shape

(3,)

In [16]:
s.shape

()

In [19]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

### Creating a tensor

In [20]:
m1 = np.array([[5,12,6],[-3,0,4]])
m1

array([[ 5, 12,  6],
       [-3,  0,  4]])

In [22]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [23]:
t = np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  0,  4]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [24]:
t.shape

(2, 2, 3)

In [27]:
t_manual = np.array([[[5,12,6],[-3,0,4]],[[9,8,7],[1,3,-5]]])
t_manual

array([[[ 5, 12,  6],
        [-3,  0,  4]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

### Operations

In [26]:
m1+m2

array([[14, 20, 13],
       [-2,  3, -1]])

In [28]:
m1-m2

array([[-4,  4, -1],
       [-4, -3,  9]])

In [29]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

In [30]:
v1-v2

array([-4, -2,  0,  2,  4])

In [31]:
v2+v1

array([6, 6, 6, 6, 6])

### Exceptions (addition with scalar)

In [32]:
m1

array([[ 5, 12,  6],
       [-3,  0,  4]])

In [33]:
m1+1

array([[ 6, 13,  7],
       [-2,  1,  5]])

In [34]:
v1

array([1, 2, 3, 4, 5])

In [35]:
v1+1

array([2, 3, 4, 5, 6])

### Transposing vectors and matrices

In [37]:
vec = np.array([[4],[7],[-3],[2]])
vec

array([[ 4],
       [ 7],
       [-3],
       [ 2]])

In [38]:
vec.T

array([[ 4,  7, -3,  2]])

In [41]:
mat = np.array([[3,8,4],[0,3,1],[9,-5,6],[7,11,34]])
mat

array([[ 3,  8,  4],
       [ 0,  3,  1],
       [ 9, -5,  6],
       [ 7, 11, 34]])

In [42]:
mat.T

array([[ 3,  0,  9,  7],
       [ 8,  3, -5, 11],
       [ 4,  1,  6, 34]])

### It only work in a shape ex. (1,4)

In [63]:
vec2 = np.array([3,5,4,8])
vec2

array([3, 5, 4, 8])

In [64]:
vec2.T

array([3, 5, 4, 8])

In [65]:
vec2.shape

(4,)

In [66]:
vec2 = vec2.reshape(1,4)
vec2

array([[3, 5, 4, 8]])

In [67]:
vec2.T

array([[3],
       [5],
       [4],
       [8]])

### Dot product vector

In [73]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [74]:
np.dot(x,y)

-66

### Dot product matrix

In [75]:
a = np.array([[5,12,6],[-3,0,14]])
b = np.array([[2,-1],[8,0],[3,0]])

In [76]:
np.dot(a,b)

array([[124,  -5],
       [ 36,   3]])

In [77]:
c = np.array([[-12,5,-5,1,6],[6,-2,0,0,-3],[10,2,0,8,0],[9,-4,8,3,-6]])
c

array([[-12,   5,  -5,   1,   6],
       [  6,  -2,   0,   0,  -3],
       [ 10,   2,   0,   8,   0],
       [  9,  -4,   8,   3,  -6]])

In [78]:
d = np.array([[6,-1],[8,-4],[2,-2],[7,4],[-6,-9]])
d

array([[ 6, -1],
       [ 8, -4],
       [ 2, -2],
       [ 7,  4],
       [-6, -9]])

In [79]:
np.dot(c,d)

array([[-71, -48],
       [ 38,  29],
       [132,  14],
       [ 95,  57]])